name: demo of a context variables
on: 
  workflow_dispatch:
jobs:
  context-variable-demo:
    runs-on: ubuntu-latest
    steps:
      - name: using the context variables
        run: echo "the user of the repository ${{github.actor}} and the repository name ${{github.repository}}"
      - name: printing all the context variables
        run: echo "${{toJson(github)}}"
