name: outputs demo 
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialising  the outputs
        id: step-1
        run: echo "version=0.0.0.5" >> GITHUB_OUTPUT 
      - name: calling the outputs
        run: echo "the version of the app is ${{ steps.step-1.outputs.version }}"
