name: reusable workflows
on: 
  workflow_call:
    inputs:
       name:
         description: enter the name
         required: true 
         type: string

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - name: greeting step
        run: echo "hai ${{ inputs.name }} welcome the team"
